d3.select('#block')
  .transition()
    .duration(1000)
    // .delay(750)
    // .ease(d3.easeBounceInOut)
    .ease(d3.easeBounceOut)
    .style('width', '200px')
  .transition()
    .duration(1000)
    .ease(d3.easeBounceOut)
    .style('height', '300px')
  .transition()
    .duration(1000)
    .ease(d3.easeQuadOut)
    .style('background-color', 'purple');
